const List<Map<String, String>> classlist = [
  {"link": "bakonyiboglarka", "name": "Bakonyi Boglárka"},
  {"link": "belevskiakos", "name": "Belevski Ákos"},
  {"link": "brassaikrisztina", "name": "Brassai Krisztina"},
  {"link": "czappgergo", "name": "Czapp Gergo"},
  {"link": "fratustamara", "name": "Fratus Tamara"},
  {"link": "greznarkevin", "name": "Greznár Kevin"},
  {"link": "harsanyimiklospal", "name": "Harsányi Miklós Pál"},
  {"link": "herhoffgergo", "name": "Herhoff Gergo"},
  {"link": "hullardorottya", "name": "Hullár Dorottya"},
  {"link": "imrebotond", "name": "Imre Botond"},
  {"link": "kacsmarcsikgabriella", "name": "Kacsmarcsik Gabriella"},
  {"link": "kalmargittaroza", "name": "Kalmár Gitta Róza"},
  {"link": "kerekessimonbalint", "name": "Kerekes Simon Bálint"},
  {"link": "kisflora", "name": "Kis Flóra"},
  {"link": "klingerdanielphilipp", "name": "Klinger Dániel Philipp"},
  {"link": "kovacsevicsmark", "name": "Kovácsevics Márk"},
  {"link": "koveremiliazsofia", "name": "Kövér Emília Zsófia"},
  {"link": "lakatosdaniel", "name": "Lakatos Dániel"},
  {"link": "magyargabor", "name": "Magyar Gábor"},
  {"link": "nagybalint", "name": "Nagy Bálint"},
  {"link": "raczbotond", "name": "Rácz Botond"},
  {"link": "simondamariszvanessza", "name": "Simon Damarisz Vanessza"},
  {"link": "szabolcsirebekaeszter", "name": "Szabolcsi Rebeka Eszter"},
  {"link": "szabolcsitamasaron", "name": "Szabolcsi Tamás Áron"},
  {"link": "tugyiviktoria", "name": "Tugyi Viktória"},
  {"link": "veresvivien", "name": "Veres Vivien"}
];
